# Generated by Django 5.0.6 on 2024-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('alternative_a', models.CharField(max_length=255)),
                ('alternative_b', models.CharField(max_length=255)),
                ('alternative_c', models.CharField(max_length=255)),
                ('alternative_d', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
