# Generated by Django 5.0.6 on 2024-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='alternative_a',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='alternative_b',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='alternative_c',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='alternative_d',
        ),
        migrations.AddField(
            model_name='quiz',
            name='alternatives',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(choices=[('A', 'Alternative A'), ('B', 'Alternative B'), ('C', 'Alternative C'), ('D', 'Alternative D')], max_length=1),
        ),
    ]
