# Generated by Django 4.1.3 on 2024-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alternative_rename_question_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
